title: M. Maggiolo's website
email: maggiolo.matteo@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A lazily made Resume/blog website about me.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  Idonotknowmyname

# Build settings
theme: minima
plugins:
  - jekyll-feed

include:
  - Gemfile
  - Gemfile.lock
