title: Matteo Maggiolo's website
subtitle: AI Engineer
email: maggiolo.matteo@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A small resume/blog website for Matteo Maggiolo
url: "https://idonotknowmyname.github.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/website-index" # the subpath of your site, e.g. /blog
github_username: Idonotknowmyname

search: true

# Build settings
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
markdown: kramdown
remote_theme: https://github.com/mmistakes/minimal-mistakes
minimal_mistakes_skin: air


# Outputting
permalink: /blog/:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /blog/page:num/


include:
  - _pages


author:
  name   : "Matteo Maggiolo"
  avatar : "/img/bio.jpeg"
  bio    : "My awesome biography constrained to a sentence or two goes here."
  links:
    - label: "Linkedin"
      icon: "fab fa-fw fa-brands fa-linkedin"
      url: "https://linkedin.com/in/matteo-maggiolo-b69366183/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Idonotknowmyname"

footer:
  links:
    - label: "Linkedin"
      icon: "fab fa-fw fa-brands fa-linkedin"
      url: "https://linkedin.com/in/matteo-maggiolo-b69366183/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Idonotknowmyname"

defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/